name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Deploy to GH Pages
        run: |
          git config user.email "keshav143420@gmail.com"
          git config user.name "keshava kotri"
          git remote set-url origin https://keshav143420:c3130c2f162f32aa2b55217698a1fb6cc0a9bfa7@github.com/keshav143420/react-unit-test-practice.git
          npm run deploy
